
version: "2"
services:

  func:
    build: ./func-in-docker
    volumes:
    - ./:/workspace
    working_dir: /workspace
    ports:
    - 7071:7071
    - 8080:8080
    - 8081:8081
    command:
    - bash
    - -cex
    - |
      mkdir /tmp/sample;
      cd /tmp/sample;
      func init --worker-runtime=node TestRuntime;
      func new --name MyHttpTrigger --template "HTTP trigger";
      sed -i 's/"authLevel": "function"/"authLevel": "anonymous"/' MyHttpTrigger/function.json
      func host start --build --port=8081;
