apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: azure-runtime
  annotations:
    origin: github.com/triggermesh/azure-runtime
spec:
  parameters:
  - name: IMAGE
    description: The URI of the image to push, including registry host
  - name: TAG
    description: Tag of the image being pushed
    default: latest
  - name: DIRECTORY
    description: The subdirectory of the workspace/repo
    default: .
  - name: FUNCTION_NAME
    description: The name of the exported function to put in the runtime (empty to use package.json)
    default: ""
  - name: SKIP_TLS_VERIFY
    description: Skip registry TLS verification at push
    default: "false"
  steps:
  - name: dockerfile
    image: gcr.io/kaniko-project/executor:debug@sha256:5a8d578dc7ff0114daadb20902bf8529f9a2257440d68ac9c6c4b7da98665ca1
    command:
    - /busybox/sh
    args:
    - -c
    - |
      cd /workspace/${DIRECTORY}
      echo "FROM projectriff/node-function-invoker:0.0.9-snapshot" > Dockerfile
      if [ -z "${FUNCTION_NAME}" ]; then
      cat <<EOF >> Dockerfile
      ENV FUNCTION_URI=/functions/
      COPY package-lock.json \${FUNCTION_URI}package-lock.json
      COPY package.json \${FUNCTION_URI}package.json
      RUN (cd \${FUNCTION_URI} && npm ci)
      COPY . \${FUNCTION_URI}
      EOF
      else
      cat <<EOF >> Dockerfile
      ENV FUNCTION_URI=/functions/${FUNCTION_NAME}
      COPY ${FUNCTION_NAME} \${FUNCTION_URI}
      EOF
      fi
      pwd
      ls -l
      cat Dockerfile
  - name: export
    image: gcr.io/kaniko-project/executor@sha256:413fe14232a5f37f02a57758fe891993df3d58114ed948b00c9b044ed2f05f45
    args:
    - --context=/workspace/${DIRECTORY}
    - --dockerfile=/workspace/${DIRECTORY}/Dockerfile
    - --destination=${IMAGE}:${TAG}
    - --skip-tls-verify=${SKIP_TLS_VERIFY}
